# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

filter_ccOER <- function(W, U, sig_lv) {
    .Call(`_comoNet_filter_ccOER`, W, U, sig_lv)
}

build_Raw <- function(iseq, dzlv, bidir = FALSE) {
    .Call(`_comoNet_build_Raw`, iseq, dzlv, bidir)
}

build_CondRaw <- function(iseq, dzlv, bidir = FALSE) {
    .Call(`_comoNet_build_CondRaw`, iseq, dzlv, bidir)
}

build_Raw_sp <- function(iseq, dzlv, bidir = FALSE) {
    .Call(`_comoNet_build_Raw_sp`, iseq, dzlv, bidir)
}

build_CondRaw_sp <- function(iseq, dzlv, bidir = FALSE) {
    .Call(`_comoNet_build_CondRaw_sp`, iseq, dzlv, bidir)
}

filter_OER <- function(A, sig_lv) {
    .Call(`_comoNet_filter_OER`, A, sig_lv)
}

filter_phi <- function(A, sig_lv) {
    .Call(`_comoNet_filter_phi`, A, sig_lv)
}

filter_dispar <- function(A, sig_lv) {
    .Call(`_comoNet_filter_dispar`, A, sig_lv)
}

